### ISSUE TITLE
Feature Request: Capability of adding constraints conditionally

### ISSUE THREAD

**Issue by emacsuser123** [langit/pymprog#1]
Hello.
I've been trying to use this library, but I've reached to a point where I need to add (or not to add) certain constraints, based on some conditions.
Is that currently possible?
My first impressions are that it is not.
Constraints seem to get added "randomly" when I use conditional statements.

To sum up, this is what I'm looking for:
```
if cond == 1:
   x[i] + y[i]  >=  z[i]
elif cond == 2:
   x[i] + y[i]  <  z[i]
else:
   x[i] + y[i]  >=  0

```
Only one (and exactly one) of these constraints should be added to the system.

Also, the same thing would be needed for objective functions.

Thanks.
-Bob V

**Comment by langit** [comment]
Hi Bob, that should work. -Jet

**Comment by emacsuser123** [comment]
Hi Jet.
Ummmmmm.
I will double-check it again.
Maybe the problem is that there can be more than one objective function,  and they appear intermixed with constraints.

Do you support multiple objective functions?

Thanks a lot.
-Bob V

**Comment by langit** [comment]
Hi Bob,  
Multiple objective functions are not supported yet, that might be the cause.  
Best, 
Jet

**Comment by langit** [comment]
To see the model you have built, you may want to turn on verbosity.

> from pymprog import *
> verbose(True)  # be verbose
